name: lint, test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      -uses: actions/checkout@v2
      -name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -name: install packages
        run: yarn install
      -name: build production
        run: yarn build:prod
      -name: lint ts
        run: yarn lint:ts
      -name: lint css
        run: yarn lint:scss
      -name: unit test
        run: yarn test:unit
      -name: build storybook
        run: yarn build-storybook
      -name: screenshot test
        run: test:ui:ci
